# Generated by Django 4.2 on 2023-06-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecode',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
