# Generated by Django 4.2 on 2023-06-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecodes', '0003_timecode_pageid_alter_timecode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecode',
            name='id',
        ),
        migrations.AlterField(
            model_name='timecode',
            name='pageId',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
