# Generated by Django 4.2 on 2023-06-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timecodes', '0004_remove_timecode_id_alter_timecode_pageid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timecode',
            old_name='pageId',
            new_name='id',
        ),
    ]
