# Generated by Django 4.2 on 2023-06-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecodes', '0005_rename_pageid_timecode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
