# Generated by Django 4.2 on 2023-06-11 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timecodes', '0006_alter_timecode_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timecode',
            old_name='id',
            new_name='pageId',
        ),
    ]
