# Generated by Django 4.2 on 2023-06-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecodes', '0007_rename_id_timecode_pageid'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecode',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
    ]
