# Generated by Django 4.2 on 2023-07-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecodes', '0009_timecode_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecode',
            name='urlImage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timecode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='timecodes/static'),
        ),
    ]
